[program:tucancha-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php84 /home/santiago/tucancha/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=santiago
numprocs=1
redirect_stderr=true
stdout_logfile=/home/santiago/tucancha/storage/logs/worker.log
stopwaitsecs=3600
