[program:tucancha-reverb]
process_name=%(program_name)s
command=php84 /home/santiago/tucancha/artisan reverb:start --host=127.0.0.1 --port=8080 --no-interaction
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=santiago
numprocs=1
redirect_stderr=true
stdout_logfile=/home/santiago/tucancha/storage/logs/reverb.log
